name: Cam Wood Photography - Social Grid
favicon: null
layout_spectrum: 0.67878
typography_spectrum: 0.79629
title: Cam Wood Photography - Social Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#637ba9'
    - '#dcd0e6'
    - '#2d3b5e'
    - '#e9a7ab'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
