name: Cam Wood Photography - Social Grid
favicon: null
layout_spectrum: 0.2468085
typography_spectrum: 0.4382979
title: Cam Wood Photography - Social Grid
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030504'
    - '#dfdbcf'
    - '#3f473c'
    - '#7d8790'
    - '#b0b1a3'
  brandStrength: 1
  lightness: 0.5638298
  saturation: 0.75
  rhythmicContrast: 0.1765957
purpose: []
